server:
  port: 9000

spring:
  application:
    name: authorization-service
  data:
    mongodb:
      uri: mongodb://localhost/qby-authorization-server
  mail:
    # Email config
    host: smtp.example.com
    port: 465
    username: user@example.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  security:
    oauth2:
      authorizationserver:
        jwk:
          rsa:
            id: 7ebd2080-02e5-4c77-bb77-e0247b93ece6
            # openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048 && openssl rsa -pubout -in private_key.pem -out public_key.pem && cat public_key.pem && cat private_key.pem
            public: |
              -----BEGIN PUBLIC KEY-----
              KEY CONTENT
              -----END PUBLIC KEY-----
            private: |
              -----BEGIN PRIVATE KEY-----
              KEY CONTENT
              -----END PRIVATE KEY-----

  graphql:
    schema:
      printer:
        enabled: true
    path: /graphql
qbychat:
  user:
    register:
      # Is confirm email required
      confirm: true
  auth:
    scopes:
      # Allowed scopes
      - openid
      - profile
      - profile.edit
      - avatar.manage
      - notification.fetch
      - conversation.join-request.process
      - conversation.join-request.list
      - sticker.favorite.manage
      - link.preview
      - conversation.join
      - conversation.create
      - conversation.start-pm
      - conversation.manage
      - search
      - bot.create
      - bot.delete
      - bot.list
      - bot.manage
      - media.upload
      - sticker.manage
      - sticker.favorite.manage
      - sticker.favorite.list
      - status.edit
      - status.read
      - message.send
      - message.edit
      - message.read
      - message.fetch
      - message.delete
