server:
  port: 8081

spring:
  application:
    name: api-service
  data:
    mongodb:
      uri: mongodb://localhost/qby-chat
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  servlet:
    multipart:
      enabled: false
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "websocket"
  graphql:
    path: /graphql

qbychat:
  user:
    temp-relations:
      # How long does a temporary relation expire? (Unit: Hours)
      expire: 1
  # Telegram Features
  # Please disable it if your region blocked Telegram
  telegram:
    enabled: false
    # Your telegram bot token
    # Create with https://t.me/BotFather
    token: tgtoken
  # Link preview features
  link:
    # How long do links expire (Unit: days)
    ttl: 7
  # OkHttp
  request:
    # The User-Agent header
    user-agent: qbychat
  # Conversation Feature
  conversation:
    invite:
      # Default invite link expire time (Unit: days)
      expire: 7
  # Search Feature
  search:
    # Allow users search medias
    media: true
    page:
      # Limit pre page
      limit: 50
  # Bot Feature
  bot:
    # Should this qbychat instance allow bots?
    state: true
    # What permission will be granted to bots?
    # Warning: DO NOT grant ADMIN permissions, otherwise bots will break your servlet
    scopes:
      - link
      - media.upload
      - avatar.manage
      - message.send
      - profile.read
      - profile.edit
      - conversation.list
