services:
  mongo:
    image: mongo:8.0.9
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=qbychat'
    volumes:
      - mongo:/data/db
    restart: no

  redis:
    image: valkey/valkey:8.1.1
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: no

  rabbitmq:
    image: rabbitmq:4-management
    restart: no
    ports:
      - "5672:5672"
      - "5552:5552"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    #      RABBITMQ_DEFAULT_VHOST: qbychat
    configs:
      - source: plugins
        uid: "100"
        gid: "101"
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  minio:
#    image: minio/minio:latest
#    container_name: qbychat-minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio:/data
#    restart: no
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: password
#    command: server /data --console-address ":9001"

configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_stream]."

volumes:
  mongo:
    driver: local
  minio:
    driver: local
  rabbitmq_data:
    driver: local
