services:
  mongo:
    image: mongo:8.0.9
    container_name: qbychat-mongo
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=qbychat'
    volumes:
      - mongo:/data/db
    restart: no

  valkey:
    image: valkey/valkey:8.1.1
    container_name: qbychat-valkey
    ports:
      - '6379:6379'
    restart: no

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: qbychat-kafka
    hostname: kafka
    restart: no
    ports:
      - '9092:9092'
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      CLUSTER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_METADATA_LOG_DIR: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: qbychat-schema-registry
    depends_on:
      - kafka
    restart: no
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

#  minio:
#    image: minio/minio:latest
#    container_name: qbychat-minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio:/data
#    restart: no
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: password
#    command: server /data --console-address ":9001"

volumes:
  mongo:
    driver: local
  minio:
    driver: local