server:
  port: 8081

spring:
  application:
    name: chat-resource
  data:
    mongodb:
      uri: mongodb://localhost/qby-chat
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://localhost:9000/oauth2/jwks

qbychat:
  link:
    ttl: 7
  request:
    user-agent: qbychat