server:
  port: 8081

spring:
  application:
    name: chat-resource
  data:
    mongodb:
      uri: mongodb://localhost/qby-chat
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://localhost:9000/oauth2/jwks
  servlet:
    multipart:
      enabled: false
  mvc:
    async:
      request-timeout: -1

qbychat:
  link:
    # How long do links expire (Unit: days)
    ttl: 7
  request:
    # The User-Agent header
    user-agent: qbychat
  conversation:
    invite:
      # Default invite link expire time (Unit: days)
      expire: 7
  search:
    # Allow users search medias
    media: true
    page:
      # Limit pre page
      limit: 50
  bot:
    # Should this qbychat instance allow bots?
    state: true
    # What permission will be granted to bots?
    # Warning: DO NOT grant ADMIN permissions, otherwise bots will break your servlet
    scopes:
      - link
      - media.upload
      - message.send
      - profile.read
      - profile.edit
      - conversation.list
