spring:
  application:
    name: gateway

server:
  port: 8080

management:
  endpoint:
    gateway:
      access: unrestricted

qbychat:
  gateway:
    address:
      # proxied API address
      api: /api
      # The auth server
      auth: http://127.0.0.1:9000