package org.qbynet.chat.entity;

public enum EventType {
    TEST,

    JOIN_CONVERSATION,
    QUIT_CONVERSATION,

    CONTACT_ONLINE,
    CONTACT_OFFLINE,
    CONTACT_INSTANT_STATUS_CHANGED, // etc. user is inputting
    CONTACT_STATUS_CHANGED,

    GROUP_ONLINE_COUNTER_CHANGED,
    GROUP_MEMBER_COUNTER_CHANGED,
    GROUP_INSTANT_STATUS_CHANGED, // etc. member is inputting

    MESSAGE_DELETED
}
