/*
 * Copyright 2011 Fabian Kessler
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.optimaize.langdetect.ngram;

/**
 * Filters those that were not generated by the old n-gram generator.
 * <p>
 * Impl is immutable.
 *
 * @author Fabian Kessler
 */
public class BackwardsCompatibleNgramFilter implements NgramFilter {

    private static final BackwardsCompatibleNgramFilter INSTANCE = new BackwardsCompatibleNgramFilter();

    private BackwardsCompatibleNgramFilter() {
    }

    public static NgramFilter getInstance() {
        return INSTANCE;
    }

    @Override
    public boolean use(String ngram) {
        switch (ngram.length()) {
            case 1:
                return ngram.charAt(0) != ' ';
            case 2:
                //all upper case
                return !Character.isUpperCase(ngram.charAt(0)) || !Character.isUpperCase(ngram.charAt(1));
            case 3:
                if (Character.isUpperCase(ngram.charAt(0)) && Character.isUpperCase(ngram.charAt(1)) && Character.isUpperCase(ngram.charAt(2))) {
                    //all upper case
                    return false;
                }
                //middle char is a space
                return ngram.charAt(1) != ' ';
            default:
                throw new UnsupportedOperationException("Unsupported n-gram length: " + ngram.length());
        }
    }

}
