spring:
  application:
    name: client
  security:
    oauth2:
      client:
        registration:
          web-chat-oidc:
            provider: spring
            client-id: web-chat
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: QbyChat web
        provider:
          spring:
            issuer-uri: http://localhost:9000
