package org.qbynet.chat.entity;

public enum EventType {
    JOIN_CONVERSATION,
    QUIT_CONVERSATION,

    CONTACT_ONLINE,
    CONTACT_OFFLINE,
    CONTACT_INSTANT_STATUS_CHANGED,
    CONTACT_STATUS_CHANGED,

    GROUP_ONLINE_COUNTER_CHANGED,
    GROUP_MEMBER_COUNTER_CHANGED,


    MESSAGE_DELETED
}
